### ISSUE TITLE
Interoperability with `std::future`

### ISSUE THREAD

**Issue by LeeHowes** [executors/futures#79] opened 2018-05-04 22:14 UTC
I think we could fairly cleanly consider:
1) standard_semi_future to be move-constructible from std::future
2) std::future to have a .via method.

The former is less intrusive but would allow implementors to optimise the interaction from one to the other design space.

Promise is less important because you can always slap it in a continuation and call its methods.

I think we could reasonably expect a standard library implementation to do this and tie the completion of the std::future to triggering a callback on the semifuture implementation without adding a blocking operation, in a way that a user could not.

**Comment by dhollman** [comment] 2018-05-05 19:05
I like option 1 better, but I don't feel like I have a firm grasp on the use cases and design constraints of `standard_semi_future`, particularly insofar as it differs from a polymorphic wrapper type (which I assume we will also need to provide).

We should also consider the implications of compatibility with `std::future`, since all compatible executors will have to interact with anything that meets the `SemiFuture` concept (and thus, indirectly, with `std::future`, which may be undesirable).

**Comment by dhollman** [comment] 2018-05-05 19:06
> I think we could reasonably expect a standard library implementation to do this and tie the completion of the std::future to triggering a callback on the semifuture implementation without adding a blocking operation, in a way that a user could not.

I guess that's the key point here. `standard_semi_future` can provide a bridge to `std::future` that users cannot.  (Which seems to be what I was missing, I guess).

**Comment by LeeHowes** [comment] 2018-05-05 19:43
The only reason for doing 2 is to make std::future a SemiFuture (with additional blocking capability) and thus bring it into the modern era.

I think we should do at least 1, potentially 2, for the 1.5 timeframe.

**Comment by brycelelbach** [comment] 2018-05-08 17:14
This is a duplicate of #15.

**Closed by brycelelbach** 2018-05-08 17:14 UTC
Labels: discussion
