### ISSUE TITLE
Functor then with Future return

### ISSUE THREAD

**Issue by LeeHowes** [executors/futures#8] opened 2018-03-21 20:27 UTC
For any given continuation function we can have three (obvious) return types:

```
f.then([](T&& t){return make_expected(t);}).then([](T&&t){...});
f.then([](T&& t){return make_semi_future(t);}).then([](T&&t){...});
f.then([](T&& t){return t;}).then([](T&&t){...});

```

All three of the above would map to the next continuation in the chain behaving correctly. An expected return value, or a thrown exception, might pass fine into an exception accepting continuation. A value return would map fine into a value-accepting continuation. 

A future would map similarly, and behave as for expected except that it would offer the opportunity to have a branch in the task graph that inserts a whole new set of nodes and makes the continuation complete asynchronously. In the above it was constructed already complete, but it need not be.

This is consistent in that we have two functor versions, where the value form can be viewed as constructing the expected type and the value/error accepting versions are syntactic sugar for the expected form. Then there is one monadic version where the (value, exception) pair is unpacked from the future, for the next function in the chain.

The question that David Hollman brought up was whether we want a functor continuation that returns a future:

`f.then([](T&& t){return make_semi_future(t);}).then([](future<T>&& f){...});
`

Is this necessary? Does it add any value to the API? 

Does it become useful for bulk_then so that we can return a bulk vector of asynchronous operations, or is this an unnecessary complication that need not really be encoded as bulk and using a parallel algorithm works just as well?

**Comment by dhollman** [comment] 2018-04-04 01:24
I'm not sure which question of mine led to this, but it's an interesting question. I think there are a couple of ways to interpret your question; are you referring to the question of whether the form:

```c++
f.then([](T&& t){return make_semi_future(t);}).then([](future<T>&& f){...});
```

should be used for error propagation, in the absence of `std::expected`, or to the possibility of chaining child-to-child dependencies:

```c++
f.then([](T&& t){ 
  return make_ready_future().then([]{ return compute_value(); });
}).then([](future<T>&& f2) {
  return f2.then([](auto&& val) { return use_value(val); });
});
```

such that the closure that executes `use_value` depends directly on the closure that executes `compute_value`?  (It doesn't make much sense in this example, but in the presence of other code and/or API boundary constraints, this sort of situation does come up).  The latter is the main reason I can see why someone would actually want a `future<future<T>>` to be returned from the first `then()`, but I'm not sure if this is what you mean here.

**Comment by brycelelbach** [comment] 2018-04-26 09:07
This sounds like a dupe of #29, except for the expected case, which I don't think we should support.

**Closed by brycelelbach** 2018-04-26 09:07 UTC
Labels: discussion
